name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TAGPREFIX: gcr.io/centering-star-245013/ev_test
  GCLOUD_AS_BASE64: ${{ secrets.GCLOUDSA }}

jobs:

  Build and Push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set current date as env variable
      run: echo "DATE=$(date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_ENV
    - name: Build Docker Image
      run: docker build . --tag $TAGPREFIX:$DATE
    - name: Connect to gcloud registry
      run: echo $GCLOUD_AS_BASE64 | base64 --decode | docker login -u _json_key --password-stdin https://gcr.io
    - name: Push Docker Image
      run:  docker push $TAGPREFIX:$DATE
    - name: Connect to cluster
      uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with: { cluster_name: cluster-1, location: europe-west2-a, credentials: ${{ secrets.GCLOUDSA }} }
    - name: Call Cluster
      run: kubectl get pods --all-namespaces