name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_REGISTRY: gcr.io/centering-star-245013/ev_test
  GCLOUD_AS_BASE64: ${{ secrets.GCLOUDSA }}
  PR_NUMBER: ${{ github.event.number }}

jobs:

  Build_and_Push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Bump version and push tag (master only)
      if: github.ref == 'refs/heads/master'
      id: semver
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set tag to current date (branches only)
      if: github.ref != 'refs/heads/master'
      run: echo "TAG=$(date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_ENV
    - name: Set tag to new semantic version (master only)
      if: github.ref == 'refs/heads/master'
      run: echo "TAG=${{ steps.semver.outputs.tag }}" >> $GITHUB_ENV

    - name: Build Docker Image
      run: docker build . --tag $DOCKER_REGISTRY:$TAG
    - name: Push Docker Image
      run:  |
        echo $GCLOUD_AS_BASE64 | base64 --decode | docker login -u _json_key --password-stdin https://gcr.io
        docker push $DOCKER_REGISTRY:$TAG
  
    - name: Connect to cluster
      if: github.ref != 'refs/heads/master'
      uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with: 
        cluster_name: cluster-1
        location: europe-west2-a
        credentials: ${{ secrets.GCLOUDSA }} }
  
    - name: Deploy Preview Env (branches only)
      if: github.ref != 'refs/heads/master'
      run: |
        sed -i "s|MY_APP_NAME|ev-fullstack-tech-test-pr-$PR_NUMBER|g" ./charts/argocd.yaml
        sed -i "s|MY_COMMITISH|$(git rev-parse --short "$GITHUB_SHA")|g" ./charts/argocd.yaml
        sed -i "s|MY_DOCKER_REGISTRY|$DOCKER_REGISTRY|g" ./charts/argocd.yaml
        sed -i "s|MY_IMAGE_TAG|$TAG|g" ./charts/argocd.yaml
        cat  ./charts/argocd.yaml
        kubectl -n argocd apply -f ./charts/argocd.yaml
  
    - name: Publish Helm Chart (master only)
      if: github.ref == 'refs/heads/master'
      run: |
        sed -i "s|MY_APP_NAME|ev-fullstack-tech-test-pr-$PR_NUMBER|g" ./charts/ev-fullstack-tech-test/values.yaml
        sed -i "s|MY_COMMITISH|$TAG|g" ./charts/ev-fullstack-tech-test/values.yaml
        sed -i "s|MY_DOCKER_REGISTRY|$DOCKER_REGISTRY|g" ./charts/ev-fullstack-tech-test/values.yaml
        sed -i "s|MY_IMAGE_TAG|$TAG|g" ./charts/ev-fullstack-tech-test/values.yaml
        helm package charts/ev-fullstack-tech-test --version $TAG
        curl -v --data-binary "@ev-fullstack-tech-test-$TAG.tgz" http://35.197.246.56:8080/api/charts

    - name: Deploy To Dev (master only)
      if: github.ref == 'refs/heads/master'
      run: |
        cd deploy
        npm ci
        APP=ev-fullstack-tech-test VERSION=$TAG TOKEN=${{ secrets.DEV_REPO_TOKEN }} npm start
